# Font
font_family         Hack Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size   10

# Cursor
cursor          none
cursor_shape    beam

cursor_blink_interval    -1

# url
detect_urls yes
url_color   #ab3b2c
url_style   curly

# window layout
remember_window_size    yes
window_padding_width    4
# initial_window_width    1366
# initial_window_height   768

active_border_color     #80e87b
inactive_border_color   #ad9b97

hide_window_decorations    yes

# tab bar
tab_bar_style   powerline
tab_bar_align   left
tab_powerline_style     angled
tab_title_template          "{index}:{title}"
active_tab_background       #80e87b
active_tab_font_style       bold
inactive_tab_background     #ad9b97

# theme
include                 ./theme.conf
background_opacity      0.79

# keymaps
map ctrl+shift+enter        new_window_with_cwd
