# General
backend = "glx";
glx-no-stencil = false;
# glx-no-rebind-pixmap = true;
detect-transient = true;
# detect-client-opacity = true;

# Shadows
shadow = true;
shadow-radius = 12;
shadow-offset-x = -9;
shadow-offset-y = -5;
shadow-exclude = [
    "QTILE_INTERNAL:32c"
];

# Opacity
opacity-rule = [
    "100:class_g = 'kitty' && focused",
    "65:class_g = 'kitty' && !focused",
    "100:class_g = 'neovide' && focused",
    "65:class_g = 'neovide' && !focused",
    "65:class_g = 'brave-browser' && !focused"
]

# Fading
fading = true;
fade-delta = 10;

# Blur
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-fixed = true;
blur-background-exclude = [
    "class_g = 'brave-browser'"
]

# Wintypes
# fade, shadow, opacity, focus, full-shadow, clip-shadow-above, redir-ignore
wintypes:
{
    /* normal = {};  */
    unknown = { shadow = false };
    desktop = { shadow = false };
    dock = { shadow = false };
    toolbar = { shadow = false };
    menu = { shadow = false };
    utility = { shadow = false };
    splash = { shadow = false };
    dialog = { shadow = false };
    dropdown_menu = { shadow = false };
    popup_menu = { shadow = false };
    tooltip = { shadow = false };
    notification = { shadow = false };
    combo = { shadow = false };
    dnd = { shadow = false };
};
