shadow = true;
shadow-radius = 15;

shadow-exclude = [
    "class_g = 'Ulauncher'"
];

opacity-rule = [
    "100:class_g = 'kitty' && focused",
    "65:class_g = 'kitty' && !focused"
]

fading = true;
fade-delta = 10;

corner-radius= 7;
rounded-corners-exclude = [
    "QTILE_INTERNAL:32c"
]
