# Font
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size   12

# Cursor
cursor          none
cursor_shape    beam
cursor_blink_interval    -1

# url
detect_urls yes
url_color   #ab3b2c
url_style   curly

# window layout
remember_window_size    no 
window_border_width     2
window_margin_width     2 4 0
window_padding_width    0
placement_strategy      center
draw_minimal_borders    no
inactive_border_color   #111111
active_border_color     #818f88

# tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_bar_align               left
tab_powerline_style         angled
tab_title_template          "{index}:{title}"
active_tab_background       #80e87b
active_tab_font_style       bold
inactive_tab_background     #ad9b97
# tab_bar_background          #4d5e5d

# theme
include                 ./theme.conf
background_opacity      0.79

# keymaps
map ctrl+enter              new_window
map ctrl+shift+enter        new_window_with_cwd
map ctrl+q                  close_window
map ctrl+up                 next_window
map ctrl+down               previous_window
map ctrl+t                  new_tab
map ctrl+shift+t            new_tab_with_cwd
map ctrl+w                  close_tab
map ctrl+1                  goto_tab 1
map ctrl+2                  goto_tab 2
map ctrl+3                  goto_tab 3
map ctrl+4                  goto_tab 4
map ctrl+5                  goto_tab 5
map ctrl+6                  goto_tab 6
map ctrl+7                  goto_tab 7
map ctrl+8                  goto_tab 8
map ctrl+9                  goto_tab 9
